spring.application.name=finalYearProject
server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/plantdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=sandhiya1312
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.mysql.console.enabled=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.thymeleaf.cache=false
